EXPLAIN CREATE TABLE IF NOT EXISTS TG_User (
	User_id INT AUTO_INCREMENT PRIMARY KEY,
	FirstName VARCHAR(100) NOT NULL,
	LastName VARCHAR(100) NOT NULL,
	Phone VARCHAR(100),
	Email VARCHAR(100) NOT NULL,
	Address VARCHAR(100),
	activeUser BOOLEAN,
	PostalCode INT,
	userRoleId INT
);
